#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

source "$SCRIPT_DIR/pkgs/lobash/src/import.bash"

import l.ask l.has

check_uninstalled_cmd() {
  local cmd=$1
  if l.has not command "$cmd" ; then
    echo "command [$cmd] is not installed. ❌"
    return 0
  else
    echo "command [$cmd] is installed. ✅"
    return 1
  fi
}

_bootstrap_common() {
  echo '[Bootstrap in common]'

  echo 'To git clone submodules'
  git submodule init
  git submodule update

  echo 'To mkdir -p general work directories'
  mkdir -p ~/{Temp,Src,Workspace,Presentations,Design,Doc,Public,Pictures,Downloads}
  mkdir -p ~/.sshrc.d

  if [[ ! -d ~/.bash_it ]] ; then
    echo 'To download bash_it'
    git clone --depth 1 https://github.com/Bash-it/bash-it.git ~/.bash_it
  fi

  if [[ ! -d ~/dotfiles ]] ; then
    echo 'To download my dotfiles'
    git clone --depth 1 --recursive git@github.com:adoyle-h/dotfiles.git ~/dotfiles
    # ~/dotfiles/install
  fi

  if command -v nvm != 'nvm' ; then
    echo 'To install nvm'
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash

    read -rp "To install NodeJS. Which version? (Defaults to node latest)" answer
    if [[ -z $answer ]]; then
      answer=node
    fi

    echo "To install node. nvm install $answer"
    nvm install $answer
  fi

  if l.ask 'To install taskbook'; then
    npm i -g taskbook
  else
    cat <<<EOF
      You can install taskbook in manually by "npm i -g taskbook"
    EOF
  fi

  if [[ ! -d ~/dotfiles/secrets ]] ; then
    echo 'To download my secrets'
    # git clone --depth 1  ~/dotfiles/secrets
  fi

  if check_uninstalled_cmd cheat ; then
    if l.ask 'To download my cheatsheet'; then
      echo 'To install cheat'
      pip install --user cheat
    fi
  fi

  if [[ ! -d ~/dotfiles/cheat ]] ; then
    if l.ask 'To download my cheatsheet'; then
      git clone --depth 1 git@github.com:adoyle-h/my-command-cheat.git ~/dotfiles/cheat
    fi
  fi

  if [[ ! -d ~/dotfiles/nvim ]] ; then
    if l.ask 'To install nvim'; then
      echo 'To download my nvim configuration'
      git clone --depth 1 git@github.com:adoyle-h/neovim-config.git ~/dotfiles/nvim
    fi
  fi

  if check_uninstalled_cmd fzf ; then
    if l.ask 'To install fzf'; then
      git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
      ~/.fzf/install
    else
      cat <<<EOF
        You can install fzf in manually by below commands.
        """
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
        ~/.fzf/install
        """
      EOF
    fi
  fi

  if check_uninstalled_cmd grip ; then
    if l.ask 'To install grip'; then
      pip install grip
    fi
  fi

  ./install

  echo 'To setup bash-custom plugins'
  a enable-plugin $(cat ./bootstraps/recommends/custom_plugins)

  echo '[Done] Bootstrap in common'
}

_bootstrap_macos() {
  echo '[Bootstrap in macos]'

  if l.has not command brew ; then
    echo 'To install homebrew'
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  brew bundle install

  echo '[Done] Bootstrap in macos'
}

_bootstrap_linux() {
  echo '[Bootstrap in linux]'
  echo '[Done] Bootstrap in linux'
}

if l.has command brew ; then
  _bootstrap_common
  _bootstrap_macos
else
  _bootstrap_common
  _bootstrap_linux
fi
