#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

one plugin disable -a
one alias disable -a
one completion disable -a

one plugin enable acme adoyle alert asdf cheat completion editor fuck fzf gettext gfw git gnutools-for-mac go gpg grep history itmz java k8s keymap lesspipe ls lua macos manbash manpage npm nvim nvm prompt python rust secrets shell vscode xcode xdg-user zl 

one alias enable avoid-mistakes cd general 

one completion enable aliases.completion cheat docker-v19 go gulp gvm keybase minikube mvn procs yarn 

echo "[All Done]"
