patch:
  schema_list:
    # 可以直接删除或注释不需要的方案，对应的 *.schema.yaml 方案文件也可以直接删除
    # 除了 t9，它依赖于 rime_ice，用九宫格别删 rime_ice.schema.yaml
    - schema: rime_ice       # 雾凇拼音（全拼）
    - schema: luna_pinyin    # 朙月拼音
    - schema: t9             # 九宫格（仓输入法）

  menu/page_size: 8

  switcher/hotkeys:
    - Control+grave # control+`

  switcher/save_options:
    - ascii_punct
    - traditionalization
    - emoji
    - full_shape
    - search_single_char

  key_binder/bindings:
    - { accept: Control+p, send: Up, when: composing }
    - { accept: Control+n, send: Down, when: composing }
    - { accept: Control+b, send: Left, when: composing }
    - { accept: Control+f, send: Right, when: composing }
    - { accept: Control+a, send: Home, when: composing }
    - { accept: Control+e, send: End, when: composing }
    - { accept: Control+d, send: Delete, when: composing }
    - { accept: Control+k, send: Shift+Delete, when: composing }
    - { accept: Control+h, send: BackSpace, when: composing }
    - { accept: Shift+Tab, send: Page_Up, when: has_menu }
    - { accept: Tab, send: Page_Down, when: has_menu }

  # 中西文切换
  #
  # good_old_caps_lock: true 切换大写. false 切换中英
  # macOS 偏好设置的优先级更高，如果勾选【使用大写锁定键切换“ABC”输入法】则始终会切换输入法。
  #
  # 切换中英：
  # 不同的选项表示：打字打到一半时按下了 CapsLock、Shift、Control 后：
  # commit_code  上屏原始的编码，然后切换到英文
  # commit_text  上屏拼出的词句，然后切换到英文
  # clear        清除未上屏内容，然后切换到英文
  # inline_ascii 切换到临时英文模式，按回车上屏后回到中文状态
  # noop         屏蔽快捷键，不切换中英，但不要屏蔽 CapsLock
  ascii_composer:
    good_old_caps_lock: true  # true | false
    switch_key:
      Caps_Lock: clear      # commit_code | commit_text | clear
      Shift_L: commit_code  # commit_code | commit_text | inline_ascii | clear | noop
      Shift_R: commit_code  # commit_code | commit_text | inline_ascii | clear | noop
      Control_L: noop       # commit_code | commit_text | inline_ascii | clear | noop
      Control_R: noop       # commit_code | commit_text | inline_ascii | clear | noop
