# For 鼠须管 (MacOS)
patch:

  style/color_scheme: ADoyle
  style/color_scheme_dark: ADoyle

  preset_color_schemes:
    ADoyle:
      name: ADoyle's color scheme
      author: ADoyle
      font_face: PingFangSC-Regular
      font_point: 18.0
      label_font_face: PingFangSC-Regular
      label_font_point: 13.0
      comment_font_face: PingFangSC-Regular
      comment_font_point: 13.0
      candidate_list_layout: linear
      text_orientation: horizontal
      inline_preedit: true
      translucency: true
      corner_radius: 2.0
      hilited_corner_radius: 2.0
      border_height: 4.0
      border_width: 12.0
      line_spacing: 8.0
      color_space: display_p3
      back_color: 0x242424
      candidate_text_color: 0xD8FFFFFF
      comment_text_color: 0x3FFFFFFF
      label_color: 0xE5BBBBBB
      hilited_candidate_back_color: 0x484848
      hilited_candidate_text_color: 0xEE944F
      hilited_comment_text_color: 0x3FFFFFFF
      hilited_candidate_label_color: 0xEE944F
      text_color: 0x3FFFFFFF
      hilited_text_color: 0xFFFFFF
