#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

# shellcheck source=var.sh
source "$SCRIPT_DIR"/var.sh

main() {
   docker build "$@" -t "$IMAGE_NAME:$IMAGE_VERSION" -f "$SCRIPT_DIR/Dockerfile" "$SCRIPT_DIR/.."
}

main "$@"
