#!/usr/bin/env bash
set -e

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: $SUB_NAME completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

get_sub_command_path() {
  COMMAND_PATH="$SUB_BIN_DIR/$1"
  if [[ ! -x "$COMMAND_PATH" ]]; then
    echo "$SUB_NAME: No such command: $1" >&2
    echo "  - No executable file: $COMMAND_PATH" >&2
    exit 1
  fi
  echo "$COMMAND_PATH"
}

COMMAND_PATH="$(get_sub_command_path "$COMMAND")"
if grep -i "^# provide sub completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
