#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

get_sub_command_path() {
  COMMAND_PATH="$SUB_BIN_DIR/$1"
  if [[ ! -x "$COMMAND_PATH" ]]; then
    echo "$SUB_NAME: No such command: $1" >&2
    echo "  - No executable file: $COMMAND_PATH" >&2
    exit 1
  fi
  echo "$COMMAND_PATH"
}

main() {
  local command="${1:-}"
  local command_path

  case "$command" in
    "" | "-h" | "--help" )
      "$SUB_BIN_DIR"/help
      ;;
    * )
      command_path="$(get_sub_command_path "$command")"
      shift
      exec "$command_path" "$@"
      ;;
  esac
}

main "$@"
