---
extends: default

rules:
    line-length: disable
    indentation:
        spaces: consistent
        indent-sequences: consistent
        check-multi-line-strings: true
    empty-lines:
        level: warning
        max: 2
        max-start: 1
    new-line-at-end-of-file: enable
