#!/usr/bin/env bash

source "$HOME/.bash_it.bash"

bash-it disable alias all
bash-it disable plugin all
bash-it disable completion all

## [alias]
bash-it enable alias osx 

## [plugin]
bash-it enable plugin nvm autojump base battery browser docker-compose docker-machine docker explain extract gif java nginx osx-timemachine proxy rvm ssh alias-completion 

## [completion]
bash-it enable completion bash-it brew bundler capistrano defaults docker-compose docker-machine docker gem go grunt makefile npm nvm pip projects rake ssh terraform tmux todo virtualbox 

echo '[bash_it reset done]'
