#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

main() {
  local brewfile="$SCRIPT_DIR"/../secrets/Brewfile

  if [[ ${1:-} == '-p' ]]; then
    export ALL_PROXY=socks5://127.0.0.1:1080
  fi

  brew bundle install -v --file="$brewfile"
}

main "$@"
