#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

image=$1

if ! [[ "$image" =~ '/' ]]; then
  image=library/$image
fi

docker pull "dockerproxy.com/$image"
docker tag "dockerproxy.com/$image" "$image"
docker rmi "dockerproxy.com/$image"
