#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:completion
if [[ "${1:-}" == --complete ]]; then
  if (( COMP_CWORD < 3 )); then
    result=$(compgen -f -- "$2")
    if [[ -d $result ]]; then
      compgen -f -- "$result/"
    else
      echo "${result[@]}"
    fi
  fi
  exit 0
fi

# one.bash:usage
if (( $# == 0 )) || [[ $1 == -h ]] || [[ $1 == --help ]]; then
  cat <<EOF
Usage: $ONE_SUB $(basename "$0") <PATH>
Desc: Upload file to tempfile storage service
EOF
  exit 0
fi


readonly URL=https://sm.ms/api/upload

main() {
  local results code url
  results=$(curl -s -X POST -F "smfile=@$1" $URL)

  if [[ $# == 1 ]]; then
    echo "$results" | jq
    return 0
  fi

  code=$(echo "$results" | jq -r '.code')

  if [[ $code != success ]]; then
    echo "Upload Failed" >&2
    echo "$results" | jq
    return 4
  fi

  url=$(echo "$results" | jq -r '.data.url')

  if [[ -z $url ]]; then
    echo "url is empty!" >&2
    echo "$results" | jq
    return 5
  fi

  if [[ ${2} == -u ]]; then
    echo "$url"
  elif [[ ${2} == -s ]]; then
    echo "$url"
  fi
}

main "$@"
