# A login shell: when you are logging in remotely to another machine via ssh. You generally need to login.
# A non-login shell: when you are already logged into your desktop and you open up the terminal app.
#
# login shell: /etc/profile > /etc/paths > [~/.bash_profile or ~/.bash_login or ~/.profile]
# non-login shell: /etc/bashrc > ~/.bashrc
#
# For OSX, all terminal apps counter intuitively open up as login shells
# bash will load bashrc, but sh does not.

[[ "$_DEBUG" == "on" ]] && echo "Now executing $HOME/.bash_profile | pwd=$(pwd)"

[[ -f "$HOME/.bashrc" ]] && . "$HOME/.bashrc"
