# ~/.bashrc: executed by bash(1) for non-login shells.

[ -n "${_BASHRC_LOADED:-}" ] && return  # Only execute this file once
readonly _BASHRC_LOADED=true
ONE_DIR=/Users/adoyle/dotfiles/others/one.bash
. "$ONE_DIR/bash/entry.bash"
