#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

sub-bin enable plugin acme alert cheat completion editor fuck fzf gettext gfw git gnutools-for-mac go gpg grep gvm history itmz java k8s keymap lesspipe ls macos manbash manpage npm nvim nvm preexec prompt python rm sed-for-mac shell tmux vscode welcome xcode zl

sub-bin enable alias cd general

sub-bin enable completion alias_completion cheat cheat_sh docker-compose.v1.24.1 docker.v19.03.5 gulp gvm keybase minikube mvn yarn

echo "[All Done]"
